### PR TITLE
Add config option for cert verification when using SSL/TLS

### LINKED ISSUE #122: Add option to specify ca certificate or disable ca certificate validation
In the latest version ca certificate verification was enabled, which breaks ldap authentication when using self-signed certificates. The solution is to add a config option to specify own ca certificate for ldap. It would also be nice to be able to disable certificate verification altogether.

### PR DESCRIPTION
**Pull request by loganp**
Fixes #122 
Adds config option to specify certificate verification.  Default value requires certificate (as done currently, thus no change to current functionality), otherwise CERT_NONE to disable certificate validation

### CODE REVIEW

**Comment by clokep** [comment]
Unfortunately this seems to have suffered some bit-rot. Could you please merge in the `main` branch? Thank you!

**Comment by reivilibre** [comment]
I resolved the conflicts for you, since it only took a minute or two and it's really my fault for going on a rampage yesterday with some of the changes ;-).

**Review by reivilibre — CHANGES_REQUESTED** [review]
This seems pretty much fine to me, though adding a mention to the README would probably be a nice addition (with some level of caution that you should only disable validation if you know the security implications).

**Review by reivilibre — APPROVED** [review]
Thanks!

**Pull request merged**
