### PR TITLE
Fetch user attributes using bind_dn

### PR DESCRIPTION
**Pull request by meskio**
Resolves: #36

### CODE REVIEW

**Comment by novalis111** [comment]
I am hitting the same issue with registration through LDAP data. This PR seems to fix it by using the users own acc to fetch additional data for account creation in synapse. This approach is much more convenient as it works with "standard" LDAP ACL w/o requiring extra ACL to search users.

**Comment by meskio** [comment]
@ara4n is there any chance to get this merged? I'm tired to have to fix that manually after every release.

**Comment by lephisto** [comment]
Is there any news on that?

**Comment by meskio** [comment]
The patch has being included in the latest version of the [package in debian](https://packages.debian.org/stretch-backports/matrix-synapse-ldap3). But I have failed in my attempts to reach out to upstream. I'm happy to hear how can I push that forward.

**Comment by erikjohnston** [comment]
Thanks! This looks to have been implemented in a refactor. Sorry for the delay in this.

**Comment by meskio** [comment]
@erikjohnston can you explain me how is the issue fixed in the refactor?

I see the cod that my pull-req is meant to patch still in the master branch: https://github.com/matrix-org/matrix-synapse-ldap3/blob/master/ldap_auth_provider.py#L499

Is the refactor somewhere else than the master branch? Can you point a concrete commit with the refactor to look?

**Comment by WanTanFao** [comment]
Bump for reviewing this. Currently not possible to Login/Register without custom ACLs for many standard OpenLDAP servers (e.g.  osixia/openldap). Would be nice to see this fixed soon :)

**Comment by openscript** [comment]
With openldap I still don't have the rights to search for a given user. Something went wrong here.

**Comment by johansmitsnl** [comment]
@openscript @WanTanFao Did you manage to fix it?

I also use osixia/openldap and I have the issue that fails my registration: `ldap_auth_provider - 208 - WARNING -  - LDAP registration failed, no result.`

**Comment by meskio** [comment]
Do this pull req solve your problems?

**Pull request closed without merging**
