### PR TITLE
Add a wrapper so that the module can be used with the new module API

### LINKED ISSUE #133: Port the module to Synapse's pluggable modules
**Is your feature request related to a problem? Please describe.**
The password_providers: module interface has been deprecated and matrix-synapse-ldap3 does not seem to support the new generic module interface.

**Describe the solution you'd like**
Could you please port the module to the new generic module interface.

**Describe alternatives you've considered**

**Additional context**
Here is the error I get if I try to use the module with the generic interface:
```
2021-11-03 08:37:00,307 - root - 345 - WARNING - main - ***** STARTING SERVER *****
2021-11-03 08:37:00,308 - root - 346 - WARNING - main - Server /opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.46.0
2021-11-03 08:37:00,484 - synapse.app._base - 214 - CRITICAL - sentinel - Error during startup
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/_base.py", line 199, in wrapper
    await cb(*args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", line 374, in start
    await _base.start(hs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/_base.py", line 390, in start
    module(config=config, api=module_api)
TypeError: __init__() got an unexpected keyword argument 'api'
```

### PR DESCRIPTION
**Pull request by reivilibre**
Fixes #133 

Alternative to #134.

### CODE REVIEW

**Review by clokep — COMMENTED** [review]
Seems OK. I think it would make sense to include the tests in this PR.

I guess it isn't doable to use the same class directly? Since the class itself doesn't know how it is registered?

**Comment by reivilibre** [comment]
> I guess it isn't doable to use the same class directly?

I did this originally, but got told to do it this way. I think this way is cleaner even if just because the callbacks need their signatures massaging through the wrappers.

**Comment by reivilibre** [comment]
@clokep I've now bundled the changes to the tests in this PR, as suggested.

**Comment by reivilibre** [comment]
> > I guess it isn't doable to use the same class directly?
> 
> I did this originally, but got told to do it this way. I think this way is cleaner even if just because the callbacks need their signatures massaging through the wrappers.

(I think we will eventually want to cut out the 'old way'; at that point it would be sensible to remove the wrapper.)

**Comment by clokep** [comment]
> (I think we will eventually want to cut out the 'old way'; at that point it would be sensible to remove the wrapper.)

But we would have to ask people to update their Synapse config again though, which is really not ideal. This is why I was asking!

**Comment by reivilibre** [comment]
> > (I think we will eventually want to cut out the 'old way'; at that point it would be sensible to remove the wrapper.)
> 
> But we would have to ask people to update their Synapse config again though, which is really not ideal. This is why I was asking!

I think we would just stick with the name with 'Module' on the end; we do that for some other modules so it wouldn't be that much out of place

**Review by clokep — APPROVED** [review]

**Pull request merged**
